project:
  type: website

website:
  title: "Leonie Monigatti"
  description: "Leonie Monigatti's portfolio and blog about Machine Learning and AI Engineering."
  site-url: https://www.leoniemonigatti.com
  cookie-consent:
    type: express
    prefs-text: "Cookie Consent"
  back-to-top-navigation: true
  page-navigation: true
  navbar: 
    search: false
    right:
      - blog.qmd
      - portfolio.qmd
  page-footer:
    left:
    - Hi, I am Leonie, a machine learning engineer and technical writer. I help developers build vector-based AI solutions. My writing focuses on machine learning and AI engineering.
    center:
      - "Copyright 2025, Leonie Monigatti" 
      - imprint.qmd
      - privacy.qmd
      - glossary.qmd
    right: 
    - icon: twitter-x
      href: https://x.com/helloiamleonie
    - icon: linkedin
      href: https://www.linkedin.com/in/804250ab/
    - icon: rss
      href: blog.xml
  open-graph: true
  twitter-card:
    site: "@helloiamleonie"
format:
  html:
    include-in-header: 
      text: | 
        <meta name="google-site-verification" content="WrLJ585fAuA85_gliEF5FdqaDHKDyeKf5PMt5dlKOKw" />
    theme:
      - default
      - styles/custom.scss
    css: styles/styles.css
    toc: true
    toc-expand: true
    toc-depth: 3



