name: Deploy Quarto Website

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 'release'

    - name: Render Quarto website
      run: quarto render

    - name: Deploy to server via SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USERNAME }}
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        onlyNewer: true
        localDir: './_site'
        remoteDir: ${{ secrets.SSH_TARGET_DIR }}
        options: '--verbose'