name: Deploy Quarto Website

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 'release'

    - name: Render Quarto website
      run: quarto render

    - name: Deploy to server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './_site/*'
        remote_path: ${{ secrets.SSH_TARGET_DIR }}
        sftp_only: true